services:
  php:
    build: 
      context: ./infra/php
    volumes:
      - ./back:/var/www/html
    depends_on: 
      - mysql
    ports:
      - "9000:9000"
  nginx:
    build: 
      context: ./infra/nginx
    volumes:
      - ./front/public:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
  mysql:
    build: 
      context: ./infra/mysql
    ports:
      - "3306:3306"